### ISSUE TITLE
Switch to boot plugin

### ISSUE THREAD

**Issue by trisberg** [projectriff-samples/s1p2017-faas-demo#3]
Once the support for loading app context with the function (https://github.com/markfisher/sk8s/issues/157) is done we should switch to a boot plugin. The maven-shade plugin doesn't include the ServiceLoader info for the JDBC drivers, had to register the driver manually.

**Comment by dsyer** [comment]
That's never been a problem for me before (and the shade plugin can be configured to add service loaders - I think the Spring Boot parent pom even does it for you).

Also see #5 for a simple way to use Boot directly instead of manually creating the JDBC stuff.
