### ISSUE TITLE
Use Riff's documentation to install Riff on GKE with RBAC

### ISSUE THREAD

**Issue by gtantachuco-pivotal** [projectriff-samples/s1p2017-faas-demo#45]
Initially, I used the instructions on this page but the demo did not work. I was able to run the demo successfully after I followed these instructions: https://projectriff.io/docs/running-on-gke-with-rbac/. Please can you either point demo users to the aforementioned page?

Thanks!

**Comment by jldec** [comment]
fixed in c1e8c293885d86237a96adeb7e06004033ae3457
